"""add stripe columns to teams table

Revision ID: 6f2efeef68f7
Revises: 20260723_proposals_team_id
Create Date: 2026-07-24 00:52:45.311526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f2efeef68f7'
down_revision: Union[str, Sequence[str], None] = '20260723_proposals_team_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calcom_integrations')
    op.drop_index(op.f('ix_leads_pool_company_title'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_industry'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_location'), table_name='leads_pool')
    op.drop_table('leads_pool')
    op.create_foreign_key(None, 'proposals', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('teams', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('subscription_tier', sa.String(), server_default='free', nullable=False))
    op.add_column('teams', sa.Column('subscription_status', sa.String(), server_default='active', nullable=False))
    op.add_column('teams', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'teams', ['stripe_subscription_id'])
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'subscription_ends_at')
    op.drop_column('teams', 'subscription_status')
    op.drop_column('teams', 'subscription_tier')
    op.drop_column('teams', 'stripe_subscription_id')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.create_table('leads_pool',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('seniority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pool_pkey'))
    )
    op.create_index(op.f('ix_leads_pool_location'), 'leads_pool', ['country', 'state', 'city'], unique=False)
    op.create_index(op.f('ix_leads_pool_industry'), 'leads_pool', ['industry'], unique=False)
    op.create_index(op.f('ix_leads_pool_company_title'), 'leads_pool', ['company_name', 'title'], unique=False)
    op.create_table('calcom_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('encrypted_api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calcom_integrations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calcom_integrations_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('calcom_integrations_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
