"""add email_verified to users

Revision ID: dd3ea42e946e
Revises: 20260709_stripe
Create Date: 2026-07-10 00:53:05.559329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd3ea42e946e'
down_revision: Union[str, Sequence[str], None] = '20260709_stripe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_revisions_proposal_id'), table_name='proposal_revisions')
    op.drop_table('proposal_revisions')
    op.drop_index(op.f('ix_leads_pool_company_name'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_country'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_email'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_full_name'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_industry'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_provider_id'), table_name='leads_pool')
    op.drop_index(op.f('ix_leads_pool_title'), table_name='leads_pool')
    op.drop_table('leads_pool')
    op.drop_table('subscriptions')
    op.drop_table('invoices')
    op.drop_constraint(op.f('uq_teams_stripe_subscription_id'), 'teams', type_='unique')
    op.drop_column('teams', 'subscription_status')
    op.drop_column('teams', 'subscription_ends_at')
    op.drop_column('teams', 'stripe_subscription_id')
    op.drop_column('teams', 'subscription_tier')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.add_column('teams', sa.Column('subscription_tier', sa.VARCHAR(), server_default=sa.text("'free'::character varying"), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('subscription_ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('subscription_status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_teams_stripe_subscription_id'), 'teams', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_invoice_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_due', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hosted_invoice_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_pdf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('invoices_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey')),
    sa.UniqueConstraint('stripe_invoice_id', name=op.f('invoices_stripe_invoice_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('canceled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('subscriptions_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey')),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('subscriptions_stripe_subscription_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('leads_pool',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('seniority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pool_pkey'))
    )
    op.create_index(op.f('ix_leads_pool_title'), 'leads_pool', ['title'], unique=False)
    op.create_index(op.f('ix_leads_pool_provider_id'), 'leads_pool', ['provider_id'], unique=False)
    op.create_index(op.f('ix_leads_pool_industry'), 'leads_pool', ['industry'], unique=False)
    op.create_index(op.f('ix_leads_pool_full_name'), 'leads_pool', ['full_name'], unique=False)
    op.create_index(op.f('ix_leads_pool_email'), 'leads_pool', ['email'], unique=False)
    op.create_index(op.f('ix_leads_pool_country'), 'leads_pool', ['country'], unique=False)
    op.create_index(op.f('ix_leads_pool_company_name'), 'leads_pool', ['company_name'], unique=False)
    op.create_table('proposal_revisions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('revision_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('proposal_revisions_proposal_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_revisions_pkey'))
    )
    op.create_index(op.f('ix_proposal_revisions_proposal_id'), 'proposal_revisions', ['proposal_id'], unique=False)
    # ### end Alembic commands ###
